version: '3.9'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example-app
    volumes:
      -  ./db/data:/var/lib/mysql
    ports:
      - "3306:3306"

